version: '3'
services:
  mysql-server:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "library"
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DB_NAME=jdbc:mysql://mysql-server:3306/library
    links:
      - mysql-server
    depends_on:
      - mysql-server
