spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      initialization-fail-timeout: 10000
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        enable_lazy_load_no_trans: true

database:
  url: ${DB_NAME:jdbc:mysql://127.0.0.1:3306/library?createDatabaseIfNotExist=true}
  username: ${DB_USER:root}
  password: ${DB_PASS:password}
