spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/library?createDatabaseIfNotExist=true
    url: jdbc:mysql://127.0.0.1:3306/library?createDatabaseIfNotExist=true
    username: root
    password: password
  liquibase:
    url: jdbc:mysql://127.0.0.1:3306/library?createDatabaseIfNotExist=true
    user: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        enable_lazy_load_no_trans: true

database:
  url: jdbc:mysql://127.0.0.1:3306/library?createDatabaseIfNotExist=true