apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-rental
spec:
  replicas: 2
  selector:
    matchLabels:
      name: library-rental
  template:
    metadata:
      labels:
        name: library-rental
    spec:
      containers:
      - name: library-rental
        image: yurizp/library
        env:
          - name: DB_NAME
            value: "?"
          - name: DB_USER
            value: "?"
          - name: DB_PASS
            value: "?"
        ports:
          - containerPort: 8080
 