apiVersion: v1
kind: Service
metadata:
  name: lb-library-rental
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: library-rental